package main

// Do not edit, this file is automatically generated.

// Defaults: scaffolding used in 'new site' command
var Defaults = map[string][]byte{
	"defaults/.gitignore": []byte(`public
node_modules`),
	"defaults/content/_index.json": []byte(`{
	"title": "My Site Homepage",
	"intro": {
		"slogan": "Welcome to a faster way to web",
		"color": "red"
	}
}`),
	"defaults/content/pages/_blueprint.json": []byte(`{
	"title": "",
	"desc": "",
	"author": ""
}`),
	"defaults/content/pages/about.json": []byte(`{
	"title": "About Me",
	"desc": "Tell us about yourself",
	"author": "Your name"
}`),
	"defaults/content/pages/contact.json": []byte(`{
	"title": "Contact",
	"desc": "Maybe add a <a href='https://plentiform.com'>plentiform</a>?",
	"author": "Your name"
}`),
	"defaults/layout/content/Index.svelte": []byte(`<script>
	export let name;
	export let allNodes;
</script>

<section id="intro">
	<img alt="plenti logo" src="/build/plenti.svg" />
	<h1>{name}</h1>
	<p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
	<h3>Recent blog posts:</h3>
	{#each allNodes as node}
		{#if node.type == 'blog'}
			<a href="{node.path}">{node.fields.title}</a>
			<br />
		{/if}
	{/each}
</section>`),
	"defaults/layout/content/Pages.svelte": []byte(`<script>
	export let allNodes;
	export let title, description;
</script>

<h1>{title}</h1>
<p>Pages template</p>
<a href="/">Back home</a>
<div>
<strong>Title:</strong><span>{title}</span>
<strong>Desc:</strong><span>{description}</span>
</div>

<h3>All nodes test:</h3>
{#each allNodes as node}
	<a href="{node.path}">{node.fields.title}</a>
{/each}`),
	"defaults/layout/ejected/Content.js": []byte(`import nodes from './nodes.js';

  class Content {
  
    constructor() {}
  
    static getNode(uri) {
      let content;
      nodes.map(node => {
        if (node.path == uri) {
          content = node;
        }
      });
      return content ? content : '';
    }
  
    static getAllNodes() {
      let content = nodes.map(node => {
        return node;
      });
      return content;
    }
  }
  
  export default Content;`),
	"defaults/layout/ejected/Router.svelte": []byte(`<Html {Route} {node} {allNodes} />

  <script>
    import Navaid from 'navaid';
    import Content from './Content.js';
    import { onDestroy } from 'svelte';
    import Html from '../global/Html.svelte';
  
    let Route, node, allNodes;
  
    let uri = location.pathname;
    node = Content.getNode(uri);
    allNodes = Content.getAllNodes();
  
    function draw(m) {
      Route = m.default;
      window.scrollTo(0, 0);
    }
  
    function track(obj) {
      uri = obj.state || obj.uri;
      if (window.ga) ga.send('pageview', { dp:uri });
  
      node = Content.getNode(uri);
      allNodes = Content.getAllNodes();
    }
  
    addEventListener('replacestate', track);
    addEventListener('pushstate', track);
    addEventListener('popstate', track);
  
    const router = Navaid('/')
      .on('/', () => import('../content/Index.svelte').then(draw))
      .on('/:slug', () => import('../content/Pages.svelte').then(draw))
      .listen();
  
    onDestroy(router.unlisten);
  </script>`),
	"defaults/layout/ejected/main.js": []byte(`import Router from './Router.svelte';

  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/jim-service-worker.js')
    .then((reg) => {
      console.log('Service Worker registration succeeded.');
    }).catch((error) => {
      console.log('Service Worker registration failed with ' + error);
    });
  } else {
    console.log('Service Workers not supported by browser')
  }
  
  const replaceContainer = function ( Component, options ) {
    const frag = document.createDocumentFragment();
    const component = new Component( Object.assign( {}, options, { target: frag } ));
    if (options.target) {
      options.target.replaceWith( frag );
    }
    return component;
  }
  
  const app = replaceContainer( Router, {
    target: document.querySelector( '#hydrate-plenti' ),
    props: {}
  });
  
  export default app;`),
	"defaults/layout/ejected/nodes.js": []byte(`// TODO: This file is temporary and needs to be removed at some point.
// It should get automatically generated by plenti based on the "content/" folder.
const content = [
    {
        "path": "/blog/post1",
        "type": "blog",
        "filename": "post1.json",
        "fields": {
            "title": "Post 1",
            "description": "First blog post."
        }
    },
    {
        "path": "/blog/post2",
        "type": "blog",
        "filename": "post2.json",
        "fields": {
            "title": "Post 2",
            "description": "Second blog post."
        }
    },
    {
        "path": "/blog/post3",
        "type": "blog",
        "filename": "post-3_has_a_long_filename.json",
        "fields": {
            "title": "Post 3",
            "description": "Third of the blog posts."
        }
    },
    {
        "path": "/about",
        "type": "pages",
        "filename": "about.json",
        "fields": {
            "title": "About Page",
            "description": "This is the about page"
        }
    },
    {
        "path": "/anything",
        "type": "pages",
        "filename": "anything.json",
        "fields": {
            "title": "Anything!",
            "description": "The amazing anything page..."
        }
    },
    {
        "path": "/",
        "type": "",
        "filename": "_index.json",
        "fields": {
            "name": "Plenti"
        }
    }
];

export default content;`),
	"defaults/layout/global/Head.svelte": []byte(`<script>
  export let title;
</script>

<head>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width,initial-scale=1'>

  <title>{ title }</title>

  <link rel='icon' type='image/png' href='/favicon.png'>
  <link rel='stylesheet' href='/build/bundle.css'>
</head>`),
	"defaults/layout/global/Html.svelte": []byte(`<script>
  import Head from './Head.svelte';
import Nav from './Nav.svelte';

export let Route, node, allNodes;

  const makeTitle = filename => {
  if (filename == '_index.json') {
    return 'Home';
  } else if (filename) {
    // Remove file extension.
    filename = filename.split('.').slice(0, -1).join('.');
    // Convert underscores and hyphens to spaces.
    filename = filename.replace(/_|-/g,' ');
    // Capitalize first letter of each word.
    filename = filename.split(' ').map((s) => s.charAt(0).toUpperCase() + s.substring(1)).join(' ');
  } 
  return filename;
  }
</script>

<html lang="en">
<Head title={makeTitle(node.filename)} />
<body>
  <Nav />
  <main>
    <svelte:component this={Route} {...node.fields} {allNodes} />
  </main>
</body>
</html>`),
	"defaults/layout/global/Nav.svelte": []byte(`<nav>
  <span id="brand"><a href="/">Home</a></span>
  <a href="/about">About</a>
  <a href="/anything">Anything</a>
</nav>`),
	"defaults/package.json": []byte(`{
    "name": "svelte-app",
    "version": "1.0.0",
    "scripts": {
      "build": "rollup -c",
      "dev": "rollup -c -w",
      "start": "sirv public"
    },
    "devDependencies": {
      "@rollup/plugin-commonjs": "^11.0.0",
      "@rollup/plugin-node-resolve": "^6.0.0",
      "rollup": "^1.20.0",
      "rollup-plugin-livereload": "^1.0.0",
      "rollup-plugin-svelte": "^5.0.3",
      "rollup-plugin-terser": "^5.1.2",
      "sirv-cli": "^0.4.4",
      "svelte": "^3.0.0"
    },
    "dependencies": {
      "navaid": "^1.0.5"
    }
}`),
	"defaults/plenti.json": []byte(`{
	"baseurl": "http://example.org/",
	"title": "My New Plenti Site",
	"types": {
		"pages": "/:filename"
	},
	"build": "public",
	"local": {
		"port": 3000
	}
}`),
	"defaults/public/index.html": []byte(`<!DOCTYPE html>
<!-- 
    TODO: this is a TEMPORARY default for the build folder.
    Once plenti is automatically creating the HTML this should be removed.
-->
	<html lang="en" id="hydrate-plenti">
	<head>
		<meta charset='utf-8'>
		<meta name='viewport' content='width=device-width,initial-scale=1'>
	
		<title>Plenti app</title>
	
		<link rel='icon' type='image/png' href='/favicon.png'>
		<link rel='stylesheet' href='/build/bundle.css'>
	</head>
	
	<body>
		<main>
		<h1>no js</h1>
		</main>
		<script type="module" src="https://unpkg.com/dimport?module" data-main="/build/spa/main.js"></script>
		<script nomodule src="https://unpkg.com/dimport/nomodule" data-main="/build/spa/main.js"></script>
	</body>
	
	
	</html>`),
	"defaults/rollup.config.js": []byte(`import svelte from 'rollup-plugin-svelte';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';

const production = !process.env.ROLLUP_WATCH;

export default [{
    input: 'layout/ejected/main.js',
    output: {
        sourcemap: true,
        format: 'esm',
        name: 'app',
        dir: 'public/build/spa'
    },
    plugins: [
        svelte({
            dev: !production,
            css: css => {
                css.write('public/build/bundle.css');
            }
        }),
        resolve({
            browser: true,
            dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
        }),
        commonjs(),
        !production && serve(),
        !production && livereload('public'),
        production && terser()
    ],
    watch: {
        clearScreen: false
    }
},
{
    input: 'layout/ejected/main.js',
    output: {
        sourcemap: true,
        format: 'cjs',
        name: 'app',
        dir: 'public/build/static'
    },
    plugins: [
        svelte({
            generate: 'ssr'
        }),
    ]
}];

function serve() {
    let started = false;

    return {
        writeBundle() {
            if (!started) {
                started = true;

                require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
                    stdio: ['ignore', 'inherit', 'inherit'],
                    shell: true
                });
            }
        }
    };
}`),
}
