package main

import (
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Reads all files in "defaults" folder and
// encodes them as string literals in generated/defaults.go
func main() {
	out, _ := os.Create("generated/defaults.go")
	out.Write([]byte("package generated"))
	out.Write([]byte("\n\n// Do not edit, this file is automatically generated."))
	out.Write([]byte("\n\n// Defaults: scaffolding used in 'new site' command"))
	out.Write([]byte("\nvar Defaults = map[string][]byte{\n"))
	filepath.Walk("defaults",
		func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if !info.IsDir() {
				out.Write([]byte("\t\"" + strings.TrimPrefix(path, "defaults") + "\": []byte(`"))
				f, _ := os.Open(path)
				io.Copy(out, f)
				out.Write([]byte("`),\n"))
			}
			return nil
		})
	out.Write([]byte("}\n"))
}
