package main

import (
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Packages static files in your Go binary.
func main() {
	// Reads all files in "defaults" folder and
	// encodes them as string literals in generated/defaults.go
	generate("defaults")
	// Reads all files in "ejected" folder and
	// encodes them as string literals in generated/ejected.go
	generate("ejected")
}

func generate(name string) {
	out, _ := os.Create("generated/" + name + ".go")
	out.Write([]byte("package generated"))
	out.Write([]byte("\n\n// Do not edit, this file is automatically generated."))
	out.Write([]byte("\n\n// " + strings.Title(name) + ": scaffolding used in 'build' command"))
	out.Write([]byte("\nvar " + strings.Title(name) + " = map[string][]byte{\n"))
	filepath.Walk(name,
		func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if !info.IsDir() {
				out.Write([]byte("\t\"" + strings.TrimPrefix(path, name) + "\": []byte(`"))
				f, _ := os.Open(path)
				io.Copy(out, f)
				out.Write([]byte("`),\n"))
			}
			return nil
		})
	out.Write([]byte("}\n"))
}
